Release 1.6.0
Reformat all commands to be more <command> <subcommand> grouped by parameters
Added a mechanishm to define main CLI commands and HELP documentation
Added Plugin Update
Added Repository
  Now there's a file where users can configure available plugins to install, so
  they don't need to install them always using the URL (that needs to be remembered).
  Also, by default, default shellx plugins are included (bundled) to easier installation.
Changed Testing Framework
Added UNIT test for all units
Added Integration Tests for all commands and ShellX Boot
Added dev.sh script to easy localy execute all local development tasks
Core libs are now POSIX compliant
Bash and ZSH Officially supported on shellx features
Documentation and Quick Start Guide

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,10 +17,17 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Run ShellCheck
-        uses: azohra/shell-linter@latest
-        with:
-          path: "shellx.sh,lib/core/*.sh,lib/shellx/*.sh,plugins/*.sh"
-          exclude-paths: "plugin-examples,hack"
+        run: |
+          bash ./hack/dev.sh lint
+
+  fmt:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Run ShellCheck
+        run: |
+          bash ./hack/dev.sh fmt
 
   version-check:
     runs-on: ubuntu-latest
@@ -37,7 +44,7 @@ jobs:
           git diff-index --name-only --diff-filter=d origin/main | grep -q -i "^lib\/" && echo "lib folder has changes"
           git diff-index --name-only --diff-filter=d origin/main | grep -q "^plugins\/" && echo "plugins folder has changes"
           git diff-index --name-only --diff-filter=d origin/main | grep -q "^shellx.sh" && echo "shellx.sh has changes"
-          
+
           if git diff-index --name-only --diff-filter=d origin/main | grep -q -i "^lib\/" || \
             git diff-index --name-only --diff-filter=d origin/main | grep -q "^plugins\/" || \
             git diff-index --name-only --diff-filter=d origin/main | grep -q "^shellx.sh"; then
@@ -57,32 +64,74 @@ jobs:
         uses: matt-usurp/validate-semver@v1
         with:
           version: ${{ steps.get-version.outputs.version }}
-      
-  test:
+  unit:
     runs-on: ubuntu-latest
     steps:
-      - name: Setup BATS
-        uses: mig4/setup-bats@v1
-        with:
-          bats-version: 1.9.0
-
       - name: Checkout code
         uses: actions/checkout@v3
-        with:
-          submodules: recursive
 
       - name: Unit Tests
         run: |
-          mkdir -p reports
-          bats --timing --report-formatter junit tests/*.bats --output reports
+          bash hack/dev.sh test-unit
+        env:
+          SHELLX_TEST_COVERAGE: "true"  # Enable coverage for this step
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Unit Tests Report     # Name of the check run which will be created
+          path: target/**/*.xml         # Path to test results
+          reporter: java-junit        # Format of test results
+
+  integration:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Integration Tests
+        run: |
+          bash hack/dev.sh test-integration
+        env:
+          SHELLX_TEST_COVERAGE: "true"  # Enable coverage for this step
 
       - name: Test Report
         uses: dorny/test-reporter@v1
         if: success() || failure()    # run this step even if previous step failed
         with:
           name: Unit Tests Report     # Name of the check run which will be created
-          path: reports/*.xml         # Path to test results
+          path: target/**/*.xml         # Path to test results
           reporter: java-junit        # Format of test results
+
+      - name: Test ShellX bootstrap
+        env:
+          SHELLX_DEBUG: yes
+          SHELLX_HOME: ${{ github.workspace }}
+        run: source shellx.sh
+
+      - name: e2e ShellX cli
+        env:
+          SHELLX_DEBUG: yes
+          SHELLX_HOME: ${{ github.workspace }}
+        run: |
+          # https://github.com/actions/toolkit/issues/766
+          echo "Enabling aliases definition"
+          shopt -s expand_aliases
+
+          echo "Bootstrapping shellx"
+          source shellx.sh
+
+          echo "Checking shellx version command"
+          shellx version
+
+          echo "Checking shellx info command"
+          shellx info
+
+  e2e:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
 
       - name: Test ShellX bootstrap
         env:
